### ISSUE TITLE
Do we really need a Hausordnung?

### ISSUE THREAD

**Issue by rralf** [Binary-Kitchen/Hausordnung#1]
Hi,

I'd like to emphatically stress that I'd like to retain from anything like a Hausordnung introducing even more rules, especially if there is no (at least not yet) a general agreement among our members. Better try to reduce rules instead of introducing even more.

Furthermore, please discuss such issues on the mailing list, before forking repositories (with our public group!). If someone tries to lookup our Hackspace and comes across this site, this might imply that this Hausordnung is applicable law, which is in deed not the case.

All hail discordia and thanks,
  Ralf

**Comment by marove2000** [comment]
Yes. This is a legal issue due to the opening of our workshop with all this sharp and pointy things.

This is also just a draft and is already discussed with our management. The rules will not apply before we've discussed this on the ML or MV. No worries :).

**Comment by PhilmacFLy** [comment]
Even though this is not my project I made according changes to the Repository. Except from that I think that the Github group is exactly there for working with it there fore I close this issue.

**Comment by rralf** [comment]
Phil already made this a private repository, thanks for that.

Few minutes ago, the description of this repo was "Die Hausordnung für Binary Kitchen e.V. und Werkstatt™", which is truly not the case. And yes, I do worry: during last months we successively introduced more and more laws and rules, which is far away from my understanding of a hackspace as such.

This begins from reasoning on how to handle other people's stuff and reaches to deciding what kind of stuff is allowed to stay in the place.

  Ralf

**Comment by rralf** [comment]
Right, github is the right place for that, but please not publically. I saw political parties failing with this concept. :)

As the topic of this issue is "Do we really need a Hausordnung" and Phil closed the issue, I guess (and hope) the answer is no ;-)

Cheers

**Comment by PhilmacFLy** [comment]
No I explicitly didn't make it a private repository because thats not my thing to decide, I just marked it as what it is, a Working Repository to work out a proposal to the MV or similar.

Its furthermore not my place to decide if we need one or not thats up for the MV to decide
